CREATE TABLE Categories (
	id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL
);

CREATE TABLE Books (
	id INT AUTO_INCREMENT PRIMARY KEY,
  categoryid INT NOT NULL,
  title VARCHAR(100) NOT NULL,
  author VARCHAR(100) NOT NULL,
  price DECIMAL(5,2) NOT NULL DEFAULT '0.00',
  _created DATETIME DEFAULT CURRENT_TIMESTAMP,
  KEY fk_categoryid_category_id_idx (categoryid),
  CONSTRAINT fk_categoryid_category_id FOREIGN KEY (categoryid) REFERENCES Categories(id) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE USERS (
	id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(60) NOT NULL,
  password VARCHAR(60) NOT NULL,
  role VARCHAR(25) DEFAULT 'admin',
  name VARCHAR(60) NOT NULL,
  _created DATETIME DEFAULT CURRENT_TIMESTAMP
);